name: item_display_and_preorder_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.4
  flutter_native_splash: ^2.3.9
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  rename_app: ^1.3.1

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/google-fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/google-fonts/Montserrat-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/google-fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/google-fonts/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/google-fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/google-fonts/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/google-fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/google-fonts/Montserrat-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/google-fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/google-fonts/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/google-fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/google-fonts/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/google-fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/google-fonts/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/google-fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/google-fonts/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/google-fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets/google-fonts/Montserrat-BlackItalic.ttf
          weight: 900
          style: italic


  assets:
    - assets/imgs/
    - assets/google-fonts/

flutter_native_splash:
  background_image: "assets/imgs/splash_screen.png"
  image: "assets/imgs/logo.png"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/imgs/logo_bg.png"